#ifndef CONSTANTS_H
#define CONSTANTS_H

const int NUMBER_OF_SHIPS = 10;
const int NUMBER_OF_SINGLEDECK_SHIPS = 4;
const int NUMBER_OF_DOUBLEDECK_SHIPS = 3;
const int NUMBER_OF_THREEDECK_SHIPS = 2;
const int NUMBER_OF_FOURDECK_SHIPS = 1;

const int FIELD_WIDTH = 10;
const int FIELD_HEIGHT = 10;


#endif // CONSTANTS_H

